### ISSUE TITLE
Microsoft Office Picture Manager

### ISSUE THREAD

**Issue by blueclouds8666** [fabiuz7/killed-by-microsoft#4]
**What's the Product's Name?**
Microsoft Office Picture Manager

**Describe the product in a single sentence.**
Microsoft Office Picture Manager is a raster graphics editor introduced in Microsoft Office 2003 and included up to Office 2010.

**When was the product launched? Provide a specific date, if possible.**
August 19, 2003

**When was the product discontinued? Provide a specific date, if possible.**
June 15, 2010 if we count Office 2010 release
April 8, 2013 if we count Office 2010 SP2
October 13, 2020 if we count Office 2010 last update before EOL (2010 is the last version with this software)

**What type of product was it? App, Service, or Hardware?**
App

**Comment by fabiuz7** [comment]
Thanks for the contribution, added https://github.com/fabiuz7/killed-by-microsoft/commit/ec9b73995e9c65395703c9eda55a8226603b5650
